// UI chrome translations for the welcome carousel and onboarding screens —
// follows the device's system language (see uiLang.js), not the language
// being studied. Language display names (Francês, Deutsch, etc.) come from
// the shared LANGUAGES config and stay as-is regardless of UI language.

export const WELCOME_TR = {
  pt: {
    tag: 'DESENVOLVIDO POR ESTUDANTES DA UFABC',
    s1Title: 'Bem-vindo ao\nPolySpeaker.',
    s1Body1: 'Uma plataforma de aprendizado de idiomas pensada do zero por estudantes da Universidade Federal do ABC — para quem quer aprender ',
    s1Bold: 'de verdade',
    s1Body2: ', não só decorar.',
    polyCaption: 'Esse é o Poly — vai te acompanhar na jornada.',
    s2Title: 'O método que a\nneurociência aprova.',
    s2Body1: 'Toda a trilha é baseada em ',
    s2Bold: 'tradução ativa',
    s2Body2: ': você vê uma frase no seu idioma e produz a resposta na língua alvo — sem múltipla escolha, sem cola.',
    studyLabel: '📖 ESTUDO DE REFERÊNCIA',
    studyPre: 'Karpicke & Roediger (2008, ',
    studyItalic: 'Science',
    studyMid: ') demonstraram que a ',
    studyBold: 'prática de recuperação ativa',
    studyEnd: ' — forçar o cérebro a produzir a resposta em vez de reconhecê-la — aumenta a retenção de longo prazo em até ',
    studyBold2: '3×',
    studyFinal: ' comparado à releitura passiva.',
    s2Small: 'Traduzir ativamente é exatamente isso: cada exercício é um treino de recuperação que consolida o idioma na memória de verdade.',
    s3Title: 'Uma trilha do zero\nao fluente.',
    s3Body: 'Cada módulo tem teoria integrada e exercícios progressivos. Você avança no seu ritmo.',
    stages: [
      { stage: 'Fundamentos', desc: 'Vocabulário, pronomes e estrutura básica' },
      { stage: 'Básico', desc: 'Verbos, tempos e o essencial para se comunicar' },
      { stage: 'Intermediário', desc: 'Subjuntivo, passiva e estruturas que diferenciam' },
      { stage: 'Avançado', desc: 'Idioms, condicionais e nuances' },
      { stage: 'Variados', desc: 'Treino livre + Diálogos Reais' },
    ],
    s4Title: 'Qual idioma quer\naprender primeiro?',
    s4Hint: '💡 Você pode adicionar outros idiomas depois — basta acessar as configurações na tela inicial do app.',
    soon: 'Em breve',
    s5Title: 'O que esperar\nde cada fase?',
    s5Body1: 'Com ',
    s5Bold: '10 minutos por dia',
    s5Body2: ', este é o caminho realista baseado em dados de aprendizado de idiomas:',
    milestones: [
      { weeks: '1–2 sem.', title: 'Primeiras frases', desc: 'Você já forma frases simples no novo idioma e entende expressões básicas.' },
      { weeks: '1 mês', title: 'Conversação básica', desc: 'Consegue se apresentar, pedir informações e entender respostas curtas.' },
      { weeks: '3 meses', title: 'Dia a dia', desc: 'Frases completas sobre rotina, preferências e situações do cotidiano.' },
      { weeks: '6 meses', title: 'Intermediário real', desc: 'Você entende e participa de conversas sobre temas variados com confiança.' },
    ],
    s5Small: 'Estes resultados são para idiomas de família latina/germânica. Mandarim pode levar o dobro — mas cada dia conta.',
    s6Title: 'Acompanhe\nsua evolução.',
    placementTitle: '🎯 Teste de nivelamento',
    placementText: 'Após criar seu perfil, você fará um breve teste. Ele identifica exatamente onde você está e posiciona você na trilha ideal — sem perder tempo com o que você já sabe.',
    freqTitle: 'Com que frequência quer reavaliar seu progresso?',
    freqOptions: [
      { id: 'weekly', label: 'Semanal', desc: 'Todo domingo — consistência máxima' },
      { id: 'biweekly', label: 'Quinzenal', desc: 'A cada 15 dias — ritmo equilibrado' },
      { id: 'monthly', label: 'Mensal', desc: 'Uma vez por mês — sem pressão' },
      { id: 'manual', label: 'Quando quiser', desc: 'Você decide a hora certa' },
    ],
    back: '← Voltar', next: 'Próximo →', selectLang: 'Selecione um idioma', createProfile: 'Criar meu perfil →', skip: 'Pular apresentação',
  },
  en: {
    tag: 'BUILT BY UFABC UNIVERSITY STUDENTS',
    s1Title: 'Welcome to\nPolySpeaker.',
    s1Body1: 'A language-learning platform built from scratch by students at Federal University of ABC — for people who want to ',
    s1Bold: 'actually learn',
    s1Body2: ', not just memorize.',
    polyCaption: 'This is Poly — your companion for the journey.',
    s2Title: 'The method\nneuroscience backs.',
    s2Body1: 'The whole path is built on ',
    s2Bold: 'active recall',
    s2Body2: ': you see a sentence in your language and produce the answer in the target one — no multiple choice, no shortcuts.',
    studyLabel: '📖 REFERENCE STUDY',
    studyPre: 'Karpicke & Roediger (2008, ',
    studyItalic: 'Science',
    studyMid: ') showed that ',
    studyBold: 'active retrieval practice',
    studyEnd: ' — forcing the brain to produce the answer instead of just recognizing it — boosts long-term retention by up to ',
    studyBold2: '3×',
    studyFinal: ' compared to passive re-reading.',
    s2Small: 'Active translation is exactly that: every exercise is a retrieval workout that locks the language into real memory.',
    s3Title: 'A path from zero\nto fluent.',
    s3Body: 'Every module pairs built-in theory with progressive exercises. You move at your own pace.',
    stages: [
      { stage: 'Fundamentals', desc: 'Vocabulary, pronouns and basic structure' },
      { stage: 'Basic', desc: 'Verbs, tenses and the essentials to communicate' },
      { stage: 'Intermediate', desc: 'Subjunctive, passive voice and finer structures' },
      { stage: 'Advanced', desc: 'Idioms, conditionals and nuance' },
      { stage: 'Mixed', desc: 'Free practice + Real Dialogues' },
    ],
    s4Title: 'Which language do you\nwant to learn first?',
    s4Hint: '💡 You can add other languages later — just open settings from the home screen.',
    soon: 'Coming soon',
    s5Title: 'What to expect\nat each stage?',
    s5Body1: 'With ',
    s5Bold: '10 minutes a day',
    s5Body2: ', here\'s a realistic path based on language-learning data:',
    milestones: [
      { weeks: '1–2 wks', title: 'First sentences', desc: 'You can already form simple sentences and understand basic expressions.' },
      { weeks: '1 month', title: 'Basic conversation', desc: 'You can introduce yourself, ask for information and understand short replies.' },
      { weeks: '3 months', title: 'Everyday life', desc: 'Full sentences about routine, preferences and everyday situations.' },
      { weeks: '6 months', title: 'Real intermediate', desc: 'You understand and take part in conversations on varied topics with confidence.' },
    ],
    s5Small: 'These results are for Latin/Germanic languages. Mandarin can take about twice as long — but every day still counts.',
    s6Title: 'Track your\nprogress.',
    placementTitle: '🎯 Placement test',
    placementText: 'After creating your profile, you\'ll take a short test. It pinpoints exactly where you are and places you on the right path — no wasted time on what you already know.',
    freqTitle: 'How often do you want to re-check your progress?',
    freqOptions: [
      { id: 'weekly', label: 'Weekly', desc: 'Every Sunday — maximum consistency' },
      { id: 'biweekly', label: 'Biweekly', desc: 'Every 15 days — balanced pace' },
      { id: 'monthly', label: 'Monthly', desc: 'Once a month — no pressure' },
      { id: 'manual', label: 'Whenever', desc: 'You decide the right time' },
    ],
    back: '← Back', next: 'Next →', selectLang: 'Select a language', createProfile: 'Create my profile →', skip: 'Skip intro',
  },
  ar: {
    tag: 'من إعداد طلاب جامعة ABC الفيدرالية',
    s1Title: 'مرحبًا بك في\nPolySpeaker.',
    s1Body1: 'منصة لتعلم اللغات صُممت من الصفر على يد طلاب الجامعة الفيدرالية لمنطقة ABC — لمن يريد ',
    s1Bold: 'التعلم الحقيقي',
    s1Body2: '، لا مجرد الحفظ.',
    polyCaption: 'هذا بولي — رفيقك في هذه الرحلة.',
    s2Title: 'الطريقة التي\nيؤكدها علم الأعصاب.',
    s2Body1: 'يعتمد المسار بالكامل على ',
    s2Bold: 'الاسترجاع النشط',
    s2Body2: ': ترى جملة بلغتك وتنتج الإجابة باللغة المستهدفة — دون اختيار من متعدد، ودون طرق مختصرة.',
    studyLabel: '📖 دراسة مرجعية',
    studyPre: 'أظهرت دراسة Karpicke & Roediger (2008, ',
    studyItalic: 'Science',
    studyMid: ') أن ',
    studyBold: 'ممارسة الاسترجاع النشط',
    studyEnd: ' — إجبار الدماغ على إنتاج الإجابة بدلًا من مجرد التعرف عليها — يرفع الاحتفاظ طويل المدى بالمعلومة حتى ',
    studyBold2: '3 أضعاف',
    studyFinal: ' مقارنة بإعادة القراءة السلبية.',
    s2Small: 'الترجمة النشطة هي بالضبط ذلك: كل تمرين هو تدريب استرجاع يرسّخ اللغة في الذاكرة الحقيقية.',
    s3Title: 'مسار من الصفر\nإلى الطلاقة.',
    s3Body: 'كل وحدة تجمع بين شرح نظري مدمج وتمارين تدريجية. تتقدم بالوتيرة التي تناسبك.',
    stages: [
      { stage: 'الأساسيات', desc: 'المفردات والضمائر والبنية الأساسية' },
      { stage: 'أساسي', desc: 'الأفعال والأزمنة وأساسيات التواصل' },
      { stage: 'متوسط', desc: 'صيغة الشرط والمبني للمجهول وبنى أدق' },
      { stage: 'متقدم', desc: 'التعبيرات الاصطلاحية والجمل الشرطية والفروق الدقيقة' },
      { stage: 'متنوع', desc: 'تدريب حر + حوارات حقيقية' },
    ],
    s4Title: 'ما اللغة التي تريد\nتعلمها أولًا؟',
    s4Hint: '💡 يمكنك إضافة لغات أخرى لاحقًا — فقط افتح الإعدادات من الشاشة الرئيسية.',
    soon: 'قريبًا',
    s5Title: 'ماذا تتوقع\nفي كل مرحلة؟',
    s5Body1: 'مع ',
    s5Bold: '10 دقائق يوميًا',
    s5Body2: '، هذا مسار واقعي مبني على بيانات تعلم اللغات:',
    milestones: [
      { weeks: '1–2 أسبوع', title: 'أول الجمل', desc: 'تستطيع بالفعل تكوين جمل بسيطة وفهم تعبيرات أساسية.' },
      { weeks: 'شهر واحد', title: 'محادثة أساسية', desc: 'تستطيع تقديم نفسك وطلب معلومات وفهم ردود قصيرة.' },
      { weeks: '3 أشهر', title: 'الحياة اليومية', desc: 'جمل كاملة عن الروتين والتفضيلات والمواقف اليومية.' },
      { weeks: '6 أشهر', title: 'مستوى متوسط حقيقي', desc: 'تفهم وتشارك في محادثات حول مواضيع متنوعة بثقة.' },
    ],
    s5Small: 'هذه النتائج للغات اللاتينية/الجرمانية. قد تستغرق الماندرين ضعف الوقت تقريبًا — لكن كل يوم له قيمته.',
    s6Title: 'تابع\nتقدمك.',
    placementTitle: '🎯 اختبار تحديد المستوى',
    placementText: 'بعد إنشاء ملفك الشخصي، ستخوض اختبارًا قصيرًا. يحدد بدقة أين أنت الآن ويضعك في المسار المناسب — دون إضاعة وقت فيما تعرفه بالفعل.',
    freqTitle: 'كم مرة تريد إعادة تقييم تقدمك؟',
    freqOptions: [
      { id: 'weekly', label: 'أسبوعيًا', desc: 'كل أحد — أقصى انتظام' },
      { id: 'biweekly', label: 'كل أسبوعين', desc: 'كل 15 يومًا — وتيرة متوازنة' },
      { id: 'monthly', label: 'شهريًا', desc: 'مرة كل شهر — دون ضغط' },
      { id: 'manual', label: 'وقتما تشاء', desc: 'أنت من يحدد الوقت المناسب' },
    ],
    back: '→ رجوع', next: 'التالي ←', selectLang: 'اختر لغة', createProfile: 'أنشئ ملفي الشخصي ←', skip: 'تخطي المقدمة',
  },
};

export const ONBOARDING_TR = {
  pt: {
    logoSub: 'Aprenda idiomas de verdade',
    step1of2: '1 de 2', step2of2: '2 de 2', lastStep: 'ÚLTIMO PASSO',
    q1: 'Qual idioma você quer aprender?',
    q1Sub: 'Começaremos com tradução ativa — o método mais eficaz.',
    soon: 'Em breve', continueBtn: 'Continuar',
    q2: lang => `Qual é o seu nível de ${lang}?`,
    q2Sub: 'Indicaremos por onde começar. Você pode mudar depois.',
    back: '← Voltar', start: 'Começar →',
  },
  en: {
    logoSub: 'Learn languages for real',
    step1of2: '1 of 2', step2of2: '2 of 2', lastStep: 'LAST STEP',
    q1: 'Which language do you want to learn?',
    q1Sub: 'We\'ll start with active recall — the most effective method.',
    soon: 'Coming soon', continueBtn: 'Continue',
    q2: lang => `What is your level of ${lang}?`,
    q2Sub: 'We\'ll suggest where to start. You can change it later.',
    back: '← Back', start: 'Start →',
  },
  ar: {
    logoSub: 'تعلّم اللغات بشكل حقيقي',
    step1of2: '1 من 2', step2of2: '2 من 2', lastStep: 'الخطوة الأخيرة',
    q1: 'ما اللغة التي تريد تعلمها؟',
    q1Sub: 'سنبدأ بالاسترجاع النشط — الطريقة الأكثر فعالية.',
    soon: 'قريبًا', continueBtn: 'متابعة',
    q2: lang => `ما مستواك في ${lang}؟`,
    q2Sub: 'سنقترح من أين تبدأ. يمكنك تغيير ذلك لاحقًا.',
    back: '→ رجوع', start: 'ابدأ ←',
  },
};
